// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { SleepArgs } from "./sleep";
export type Sleep = import("./sleep").Sleep;
export const Sleep: typeof import("./sleep").Sleep = null as any;
utilities.lazyLoad(exports, ["Sleep"], () => require("./sleep"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "azure-ext:time:Sleep":
                return new Sleep(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("azure-ext", "time", _module)
