// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azureext.certificate;




public final class KeyVaultCertificateArgs extends com.pulumi.resources.ResourceArgs {

    public static final KeyVaultCertificateArgs Empty = new KeyVaultCertificateArgs();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private KeyVaultCertificateArgs $;

        public Builder() {
            $ = new KeyVaultCertificateArgs();
        }
        public KeyVaultCertificateArgs build() {
            return $;
        }
    }

}
