# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_azure_ext.certificate as __certificate
    certificate = __certificate
    import pulumi_azure_ext.config as __config
    config = __config
else:
    certificate = _utilities.lazy_import('pulumi_azure_ext.certificate')
    config = _utilities.lazy_import('pulumi_azure_ext.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "azure-ext",
  "mod": "certificate",
  "fqn": "pulumi_azure_ext.certificate",
  "classes": {
   "azure-ext:certificate:KeyVaultCertificate": "KeyVaultCertificate"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "azure-ext",
  "token": "pulumi:providers:azure-ext",
  "fqn": "pulumi_azure_ext",
  "class": "Provider"
 }
]
"""
)
