// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azureext;

import com.pulumi.core.internal.Codegen;
import java.lang.String;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("azure-ext");
    public String version() {
        return Codegen.stringProp("version").config(config).require();
    }
}
