// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azureext.time;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class SleepArgs extends com.pulumi.resources.ResourceArgs {

    public static final SleepArgs Empty = new SleepArgs();

    @Import(name="duration", required=true)
    private Output<String> duration;

    public Output<String> duration() {
        return this.duration;
    }

    private SleepArgs() {}

    private SleepArgs(SleepArgs $) {
        this.duration = $.duration;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SleepArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SleepArgs $;

        public Builder() {
            $ = new SleepArgs();
        }

        public Builder(SleepArgs defaults) {
            $ = new SleepArgs(Objects.requireNonNull(defaults));
        }

        public Builder duration(Output<String> duration) {
            $.duration = duration;
            return this;
        }

        public Builder duration(String duration) {
            return duration(Output.of(duration));
        }

        public SleepArgs build() {
            if ($.duration == null) {
                throw new MissingRequiredPropertyException("SleepArgs", "duration");
            }
            return $;
        }
    }

}
