// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azureext.time;

import com.pulumi.azureext.Utilities;
import com.pulumi.azureext.time.SleepArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * Sleep for a specified amount of time.
 * 
 */
@ResourceType(type="azure-ext:time:Sleep")
public class Sleep extends com.pulumi.resources.CustomResource {
    @Export(name="duration", refs={String.class}, tree="[0]")
    private Output<String> duration;

    public Output<String> duration() {
        return this.duration;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Sleep(String name) {
        this(name, SleepArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Sleep(String name, SleepArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Sleep(String name, SleepArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("azure-ext:time:Sleep", name, args == null ? SleepArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private Sleep(String name, Output<String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("azure-ext:time:Sleep", name, null, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Sleep get(String name, Output<String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Sleep(name, id, options);
    }
}
