// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { KeyVaultCertificateArgs } from "./keyVaultCertificate";
export type KeyVaultCertificate = import("./keyVaultCertificate").KeyVaultCertificate;
export const KeyVaultCertificate: typeof import("./keyVaultCertificate").KeyVaultCertificate = null as any;
utilities.lazyLoad(exports, ["KeyVaultCertificate"], () => require("./keyVaultCertificate"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "azure-ext:certificate:KeyVaultCertificate":
                return new KeyVaultCertificate(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("azure-ext", "certificate", _module)
